name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 8 and Maven
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '8'
        maven-version: '3.8.4'

    - name: Build Java application
      run: mvn clean package

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install
        aws --version

    - name: Upload to S3
      uses: aws-actions/aws-cli@v2
      with:
        args: s3 cp target/my-java-app-1.0-SNAPSHOT.jar s3://demo-pocaws/

    - name: Deploy to Lambda
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Update Lambda function
      run: aws lambda update-function-code --function-name poc-function-name --s3-bucket demo-pocaws --s3-key my-java-app-1.0-SNAPSHOT.jar
