name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Maven
      uses: apache/maven@v3

    - name: Build Java application
      run: mvn package -DskipTests=true

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Upload to S3
      uses: aws-actions/aws-cli@v2
      with:
        args: s3 cp target/demo-*.jar s3://demo-pocaws/

    - name: Deploy to Lambda
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Update Lambda function
      run: aws lambda update-function-code --function-name poc-func --s3-bucket demo-pocaws --s3-key demo-*.jar
