name: Build, Deploy, and Update Lambda

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '8'

    - name: Build with Maven
      run: mvn clean package

   
    - name: Upload ZIP to S3
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1
    - run: aws s3 cp $GITHUB_WORKSPACE/target/poc-1.0-SNAPSHOT.zip s3://demo-pocaws/poc-1.0-SNAPSHOT.zip

  deploy-lambda:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Upload ZIP to Lambda Function
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1
    - run: aws lambda update-function-code --function-name pocfunc --s3-bucket demo-pocaws --s3-key poc-1.0-SNAPSHOT.zip
