name: Build, Deploy, and Update Lambda

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '1.8'

    - name: Build with Maven
      run: mvn clean package

    - name: Create ZIP file
      run: zip -j target/my-java-app-1.0-SNAPSHOT.zip target/my-java-app-1.0-SNAPSHOT.jar

    
    - name: Upload ZIP to S3
      uses: aws-actions/amazon-s3-upload-action@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1
        src: target/my-java-app-1.0-SNAPSHOT.zip
        bucket-name: demo-pocaws
        object-name: my-java-app-1.0-SNAPSHOT.zip

  deploy-lambda:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Upload ZIP to Lambda Function
      uses: aws-actions/aws-cli@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1
        script: |
          aws lambda update-function-code --function-name pocfunc --s3-bucket demo-pocaws --s3-key my-java-app-1.0-SNAPSHOT.zip
