name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 8 and Maven
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '8'
        maven-version: '3.8.4'

    - name: Build Java application
      run: mvn clean package

  deploy:
   runs-on: ubuntu-latest
   needs: build

   steps:
   - name: Debug - List Directory Contents
     run: ls -R

   - name: Deploy to Lambda and Upload to S3
     run: |
       # Install AWS CLI
       sudo apt-get install -y awscli

       # Configure AWS CLI
       aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
       aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
       aws configure set region ap-south-1

       # Navigate to the correct directory
       cd /poc-demo/poc-demo/target/

       # Upload to S3
       aws s3 cp target/my-java-app-1.0-SNAPSHOT.jar s3://demo-pocaws/

       # Update Lambda function
       aws lambda update-function-code --function-name poc-function-name --s3-bucket demo-pocaws --s3-key my-java-app-1.0-SNAPSHOT.jar
