name: Build, Deploy, and Update Lambda

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '8'  # Use the desired version from the available versions

    - name: Debug Environment
      run: |
        echo "JAVA_HOME: $JAVA_HOME"
        echo "M2_HOME: $M2_HOME"
        env

    - name: Disable Maven Cache
      run: |
        export MAVEN_OPTS="-Dmaven.repo.local=${GITHUB_WORKSPACE}/.m2/repository"

    - name: Build with Maven
      run: mvn clean package

    - name: Debug Target Directory
      run: |
        ls -R target
