name: Java with Maven and AWS

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven

    - name: Build with Maven
      run: mvn clean package

    - name: Zip JAR file
      run: zip target/spring-boot-2-hello-world.jar.zip target/spring-boot-2-hello-world.jar

    - name: Upload ZIP to S3
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'your-aws-region'
    - run: aws s3 cp target/spring-boot-2-hello-world.jar.zip s3://demo-pocaws/

   